version: "3.8"

services:
  # Backend API
  face-recg-api:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/FACE-RECG-DB"
      REDISTOGO_URL: "redis://redis:6379"
      PORT: 4000
      JWT_SECRET: "${JWT_SECRET}"
      CLARIFAI_API_KEY: "${CLARIFAI_API_KEY}"
    volumes:
      - ./:/app

  # Postgres
  postgres:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: FACE-RECG-DB
      POSTGRES_HOST: postgres

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
